/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Menu.MenuDirectory;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sravya
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private CustomerDirectory customerDirectory;
    private RestaurantDirectory restaurantDirectory;
    private DeliveryManDirectory deliveryManDirectory;
    private MenuDirectory menuDirectory;
    private OrderDirectory orderDirectory;
    private static int count = 1;

    
    public CustomerAreaJPanel(
            JPanel workArea, 
            UserAccount account, 
            EcoSystem ecoSystem,
            CustomerDirectory customerDirectory,
            RestaurantDirectory restaurantDirectory,
            DeliveryManDirectory deliveryManDirectory,
            MenuDirectory menuDirectory,
            OrderDirectory orderDirectory) {
        initComponents();
        this.setSize(931, 723);
        this.workArea = workArea;
        this.userAccount = account;
        this.ecoSystem = ecoSystem;
        this.customerDirectory = ecoSystem.getCustomerDirectory();
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        this.menuDirectory = ecoSystem.getMenuDirectory();
        this.deliveryManDirectory = ecoSystem.getDeliveryManDirectory();
        this.orderDirectory = ecoSystem.getOrderDirectory();
        valueLabel.setText(account.getUsername());
        
        populateRequestTable();
        populateRestaurantCombo();
    }
    
    public void populateRequestTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
        
        model.setRowCount(0);
        for (Order order : ecoSystem.getOrderDirectory().getOrderList()){
            if(userAccount.getEmployee().getName().equals(order.getCustomer().getName())){
            Object[] row = new Object[8];
                row[0] = order;
                row[1] = order.getMenu().getDishName();
                row[2] = order.getQuantity() * order.getMenu().getPrice();
                row[3] = order.getRestaurant().getRestaurantName();
                row[4] = order.getMessage();
                row[5] = order.getCustomer().getName();
                row[6] = order.getOrderStatus();
                row[7] = order.getQuantity();
            
                model.addRow(row);
            }
        } 
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDishes.getModel();
        dtm.setRowCount(0);
        String restaurantName = cmbRestaurants.getSelectedItem().toString();
        Restaurant restaurant = ecoSystem.getRestaurantDirectory().getRestaurant(restaurantName);
        for(Menu menu : ecoSystem.getMenuDirectory().getMenuList()){
            if(restaurant.getRestaurantName().equals(menu.getRestaurantName())) {
                Object [] row = new Object[2];
                row[0] = menu;
                row[1] = menu.getPrice();
                dtm.addRow(row);
            }
        }
    }
    
    public void populateRestaurantCombo() {
        cmbRestaurants.removeAllItems();
        cmbRestaurants.addItem("  ");
        for(Restaurant res : ecoSystem.getRestaurantDirectory().getRestaurantList()) {
            cmbRestaurants.addItem(res.getRestaurantName());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowMenu = new javax.swing.JButton();
        lblCustomer = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDishes = new javax.swing.JTable();
        cmbRestaurants = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtComment = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowMenu.setText("Show Menu");
        btnShowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMenuActionPerformed(evt);
            }
        });
        add(btnShowMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 113, -1, -1));

        lblCustomer.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblCustomer.setText("Customer:");
        add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 21, 158, 26));

        tblDishes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDishes.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblDishes.setSelectionForeground(new java.awt.Color(0, 51, 255));
        jScrollPane2.setViewportView(tblDishes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 159, 709, 149));

        cmbRestaurants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRestaurantsActionPerformed(evt);
            }
        });
        add(cmbRestaurants, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 114, 144, -1));

        jLabel1.setText("Quantity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 353, -1, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 347, 90, -1));

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Dish Name", "Price", "Restaurant", "Comment", "Delivery By", "Order Status", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorkRequests.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblWorkRequests.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(tblWorkRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 910, 154));

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 347, 110, -1));

        jLabel2.setText("Your Comment:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 636, -1, -1));

        btnSubmit.setText("Submit Comment");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 676, -1, -1));
        add(txtComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 630, 204, -1));

        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 676, -1, -1));

        jLabel3.setText("Select Restaurant:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 119, -1, -1));

        jLabel4.setText("Your Cart");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 69, -1, -1));

        jLabel5.setText("Your Order History");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 424, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sravy\\OneDrive\\Pictures\\A4 pics\\feedingamerica-dd")); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -140, 1230, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMenuActionPerformed
        // TODO add your handling code here:
        if(cmbRestaurants.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a restaurant");
            return;
        }
        populateTable();
    }//GEN-LAST:event_btnShowMenuActionPerformed

    private void cmbRestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRestaurantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRestaurantsActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDishes.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int quantity = Integer.parseInt(txtQuantity.getText());
        String restaurantName = cmbRestaurants.getSelectedItem().toString();
        Restaurant restaurant = ecoSystem.getRestaurantDirectory().getRestaurant(restaurantName);
        Customer customer = ecoSystem.getCustomerDirectory().getCustomer(userAccount.getEmployee().getName());
        Menu menu = (Menu) tblDishes.getValueAt(selectedRow, 0);
        String status = "Order Placed";

        Order order = ecoSystem.getOrderDirectory().createOrder();
        order.setCustomer(customer);
        order.setOrderID(String.valueOf(count++));
        order.setQuantity(quantity);
        order.setMenu(menu);
        order.setRestaurant(restaurant);
        order.setOrderStatus(status);
        order.setAssign(false);

        JOptionPane.showMessageDialog(null,"Your order has been placed!");
        populateRequestTable();

    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if(txtComment.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Field cannot be empty");
            return;
        }

        int selectedRow = tblWorkRequests.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Order order = (Order)tblWorkRequests.getValueAt(selectedRow, 0);
        order.setMessage(txtComment.getText());
        populateRequestTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnShowMenu;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbRestaurants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JTable tblDishes;
    private javax.swing.JTable tblWorkRequests;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
