/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Sravya
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    CustomerDirectory customerDirectory;
    RestaurantDirectory restaurantDirectory;
    DeliveryManDirectory deliveryManDirectory;

    
    public SystemAdminWorkAreaJPanel(
            JPanel userProcessContainer, 
            EcoSystem ecoSystem, 
            CustomerDirectory customerDirectory, 
            RestaurantDirectory restaurantDirectory, 
            DeliveryManDirectory deliveryManDirectory) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = EcoSystem.getEcoSystemInstance();
        this.customerDirectory = ecoSystem.getCustomerDirectory();
        this.deliveryManDirectory = ecoSystem.getDeliveryManDirectory();
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model = (DefaultTreeModel)jTree.getModel();
       // Add the code for draw your system structure shown by JTree
       
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("System Admin");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        ArrayList<Customer> customerList = this.ecoSystem.getCustomerDirectory().getCustomerList();
        ArrayList<DeliveryMan> deliveryList = this.ecoSystem.getDeliveryManDirectory().getDeliveryManList();
        ArrayList<Restaurant> restaurantList = this.ecoSystem.getRestaurantDirectory().getRestaurantList();
        
        DefaultMutableTreeNode customerListNode = new DefaultMutableTreeNode("Customer");
        DefaultMutableTreeNode deliveryManListNode  = new DefaultMutableTreeNode("Delivery Man");
        DefaultMutableTreeNode restaurantListNode = new DefaultMutableTreeNode("Restaurant");
        networks.insert(customerListNode, 0);
        networks.insert(deliveryManListNode, 1);
        networks.insert(restaurantListNode, 2);
        
        DefaultMutableTreeNode customerNode;
        DefaultMutableTreeNode deliveryManNode;
        DefaultMutableTreeNode restaurantNode;
        
        Customer customer;
        DeliveryMan deliveryMan;
        Restaurant restaurant;
        
        for(int i = 0; i < customerList.size(); i++){
            customer = customerList.get(i);
            customerNode = new DefaultMutableTreeNode(customer.getName());
            customerListNode.insert(customerNode, i);
            
        }    
        for(int j = 0; j < deliveryList.size(); j++){
            deliveryMan = deliveryList.get(j);
            deliveryManNode = new DefaultMutableTreeNode(deliveryMan.getName());
            deliveryManListNode.insert(deliveryManNode, j);
        }        
                
        for(int k = 0; k < restaurantList.size(); k++){
            restaurant = restaurantList.get(k);
            restaurantNode = new DefaultMutableTreeNode(restaurant.getRestaurantName());
            restaurantListNode.insert(restaurantNode, k);
        }
       
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnManageCustomers = new javax.swing.JButton();
        btnManageRestaurant = new javax.swing.JButton();
        btnManageDeliveryMan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 350, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Selected Node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        lblSelectedNode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 14, -1, -1));

        btnManageCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageCustomers.setIcon(new javax.swing.ImageIcon("C:\\Users\\sravy\\OneDrive\\Pictures\\A4 pics\\mng customers.png")); // NOI18N
        btnManageCustomers.setText("Manage All Customers");
        btnManageCustomers.setContentAreaFilled(false);
        btnManageCustomers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageCustomers.setOpaque(true);
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnManageRestaurant.setBackground(new java.awt.Color(255, 255, 255));
        btnManageRestaurant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageRestaurant.setIcon(new javax.swing.ImageIcon("C:\\Users\\sravy\\OneDrive\\Pictures\\A4 pics\\res.png")); // NOI18N
        btnManageRestaurant.setText("Manage Restaurants");
        btnManageRestaurant.setContentAreaFilled(false);
        btnManageRestaurant.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageRestaurant.setOpaque(true);
        btnManageRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRestaurantActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        btnManageDeliveryMan.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDeliveryMan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageDeliveryMan.setIcon(new javax.swing.ImageIcon("C:\\Users\\sravy\\OneDrive\\Pictures\\A4 pics\\icons8-user-male-64.png")); // NOI18N
        btnManageDeliveryMan.setText("Manage Delivery Men");
        btnManageDeliveryMan.setContentAreaFilled(false);
        btnManageDeliveryMan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageDeliveryMan.setOpaque(true);
        btnManageDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveryManActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sakura-background.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
       
        ManageCustomer manageCustomersJPanel = new ManageCustomer(userProcessContainer, ecoSystem, customerDirectory);
        userProcessContainer.add("ManageCustomersJPanel", manageCustomersJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnManageRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestaurantActionPerformed
        ManageRestaurant manageRestaurantJPanel = new ManageRestaurant(userProcessContainer, ecoSystem, restaurantDirectory);
        userProcessContainer.add("ManageRestaurantJPanel",manageRestaurantJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRestaurantActionPerformed

    private void btnManageDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveryManActionPerformed
        ManageDeliveryMan manageDeliveryManJPanel = new ManageDeliveryMan(userProcessContainer, ecoSystem, deliveryManDirectory);
        userProcessContainer.add("ManageDeliveryManJPanel",manageDeliveryManJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliveryManActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
        if(selectedNode!= null){
            lblSelectedNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageDeliveryMan;
    private javax.swing.JButton btnManageRestaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
